vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.autoindent = true
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.scrolloff = 9
vim.opt.title = true
vim.opt.titlestring = "%{expand(\"%:~:.:h\")}/%t"
vim.opt.signcolumn = "yes"
vim.opt.termguicolors = true
vim.opt.foldmethod = "indent"
vim.opt.foldlevelstart = 10
vim.opt.colorcolumn = "100"
vim.cmd 'colorscheme ozdark'
