local M = {}

function M.load()
  vim.api.nvim_set_hl(0, "Pmenu", { bg = OzdaluColors.purples.neutral, fg =OzdaluColors.white })
  vim.api.nvim_set_hl(0, "PmenuSel", { bg = OzdaluColors.purples.light, fg = OzdaluColors.black })
  vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
  vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" })
  vim.api.nvim_set_hl(0, "Visual", { bg = OzdaluColors.purples.neutral, fg = OzdaluColors.white })
  vim.api.nvim_set_hl(0, "SignColumn", { bg = "none" })
  vim.api.nvim_set_hl(0, "ColorColumn", { bg = OzdaluColors.reds.neutral })
  vim.api.nvim_set_hl(0, "CursorLine", { bg = OzdaluColors.purples.dark })
  vim.api.nvim_set_hl(0, "LineNr", { bg = "none", fg = OzdaluColors.oranges.light })
  vim.api.nvim_set_hl(0, "EndOfBuffer", { bg = "none", fg = OzdaluColors.blues.neutral })
  vim.api.nvim_set_hl(0, "Search", { bg = OzdaluColors.oranges.light, fg = OzdaluColors.black })
  vim.api.nvim_set_hl(0, "CurSearch", { link = "Search" })
  vim.api.nvim_set_hl(0, "Folded", { bg = OzdaluColors.greys.neutral , fg = OzdaluColors.blues.light })
  vim.api.nvim_set_hl(0, "Title", { fg = OzdaluColors.purples.light })
  vim.api.nvim_set_hl(0, "MatchParen", { bg = OzdaluColors.blues.neutral, fg = OzdaluColors.white })
  vim.api.nvim_set_hl(0, "Directory", { fg = OzdaluColors.blues.light })
  vim.api.nvim_set_hl(0, "Added", { fg = OzdaluColors.green })
  vim.api.nvim_set_hl(0, "Changed", {  fg = OzdaluColors.purples.neutral, bg = "none"  })
  vim.api.nvim_set_hl(0, "Removed", {  fg = OzdaluColors.reds.light, bg = "none" })
  vim.api.nvim_set_hl(0, "WinSeparator", { fg = OzdaluColors.white, bg = "none" })
  vim.api.nvim_set_hl(0, "StatusLineNC", { fg = OzdaluColors.white, bg = OzdaluColors.black  })

  vim.api.nvim_set_hl(0, "Statement", { fg = OzdaluColors.oranges.neutral })
  vim.api.nvim_set_hl(0, "Constant", { fg = OzdaluColors.oranges.neutral })
  vim.api.nvim_set_hl(0, "Identifier", { fg = OzdaluColors.blues.light})
  vim.api.nvim_set_hl(0, "Function", { link = "Identifier" })
  vim.api.nvim_set_hl(0, "Statement", { fg = OzdaluColors.oranges.light, bold = true })
  vim.api.nvim_set_hl(0, "Special", { fg = OzdaluColors.oranges.neutral })
  vim.api.nvim_set_hl(0, "Type", { fg = OzdaluColors.green, bold = true})
  vim.api.nvim_set_hl(0, "Number", { fg = OzdaluColors.purples.light })
  vim.api.nvim_set_hl(0, "String", { fg = OzdaluColors.specials.salmon })
  vim.api.nvim_set_hl(0, "Comment", { fg = OzdaluColors.purples.neutral})
  vim.api.nvim_set_hl(0, "Operator", { fg = OzdaluColors.greys.light })
  vim.api.nvim_set_hl(0, "Delimiter", { fg = OzdaluColors.greys.light })
  vim.api.nvim_set_hl(0, "Question", { fg = OzdaluColors.greys.light })
  vim.api.nvim_set_hl(0, "Todo", { fg = OzdaluColors.blues.normal })
  vim.api.nvim_set_hl(0, "Preproc", { fg = OzdaluColors.blues.light })
  vim.api.nvim_set_hl(0, "ErrorMsg", { fg = OzdaluColors.reds.light})
  vim.api.nvim_set_hl(0, "DiagnosticError", { link = "ErrorMsg" })
  vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = OzdaluColors.reds.neutral})
  vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = OzdaluColors.greys.neutral})

  vim.api.nvim_set_hl(0, "@variable.builtin", { fg = OzdaluColors.purples.light, italic = true })
  vim.api.nvim_set_hl(0, "@type.builtin", { fg = OzdaluColors.green, bold = true, italic = true })
  vim.api.nvim_set_hl(0, "@property", { fg = OzdaluColors.purples.light })
  vim.api.nvim_set_hl(0, "@lsp.type.property", { link = "@property" })
  vim.api.nvim_set_hl(0, "@variable", { fg = OzdaluColors.white })
  vim.api.nvim_set_hl(0, "@lsp.type.variable", { link = "@variable" })
  vim.api.nvim_set_hl(0, "@parameter", { link = "@variable" })
  vim.api.nvim_set_hl(0, "@lsp.type.parameter", { link = "@parameter" })

  -- Go TreeSitter highlights
  vim.api.nvim_set_hl(0, "@include.go", { fg = OzdaluColors.purples.light })
  vim.api.nvim_set_hl(0, "@field.go", { fg = OzdaluColors.white })
  vim.api.nvim_set_hl(0, "@type.builtin.go", { fg = OzdaluColors.green, italic = true})

  -- Lualine highlights
	vim.api.nvim_set_hl(0, "lualine_b_diff_modified_insert", { fg = OzdaluColors.blues.dark, bg = OzdaluColors.oranges.neutral})
	vim.api.nvim_set_hl(0, "lualine_b_diff_added_insert", { fg = '#007821', bg = OzdaluColors.oranges.neutral })
	vim.api.nvim_set_hl(0, "lualine_b_diff_modified_normal", { fg = OzdaluColors.purples.light, bg = OzdaluColors.purples.neutral})
	vim.api.nvim_set_hl(0, "lualine_b_diff_removed_normal", { fg = OzdaluColors.blues.light, bg = OzdaluColors.purples.neutral })
	vim.api.nvim_set_hl(0, "lualine_b_diagnostic_warn_insert", { fg = OzdaluColors.reds.dark, bg = OzdaluColors.oranges.neutral })
	vim.api.nvim_set_hl(0, "lualine_b_diagnostic_info_insert", { fg = OzdaluColors.blues.dark, bg = OzdaluColors.oranges.neutral })
	vim.api.nvim_set_hl(0, "lualine_b_diagnostic_hint_insert", { fg = OzdaluColors.purples.dark, bg = OzdaluColors.oranges.neutral })
end

return M
